image: jangrewe/gitlab-ci-android

cache:
  key: ${CI_PROJECT_ID}
  paths:
    - .gradle/

before_script:
  - export GRADLE_USER_HOME=/cache/.gradle
  - chmod +x ./gradlew

stages:
  - build
  - deploy

# 提交代码自动编译
#build:
#  stage: build # 表示 build 阶段执行的任务
#  only:
#    - func_dev # 只有在 dev_tps_demo 分支有提交时才执行任务
#  script:
#    - ./gradlew assembleDebug # 由 runner 执行的 shell 脚本，这里是执行 gradle 脚本
#  tags:
#    - android # 指定脚本在有 android 标签的 runner 上运行


# 打debug包
debug:
  stage: build
  only:
    - func_v2.5
  script:
    - ./gradlew assembleDebug
    - curl "https://oapi.dingtalk.com/robot/send?access_token=4946a9d8a018e6442963ed388ff3b6c1459850cd8f316d5f1796528f38405758" \-H 'Content-Type:application/json' \-d '{"msgtype":"text","text":{"content":"android 米易通物联网 debug version build success"},"at":{"atMobiles":["13915272257"]}}'
  artifacts:
    paths:
      - app/build/outputs/apk/
  tags:
    - android   # 指定脚本在有 android 标签的 runner 上运行


# 打release包
beta:
  stage: build
  only:
    - develop_v2.5
  script:
    - ./gradlew assembleRelease
    - curl "https://oapi.dingtalk.com/robot/send?access_token=4946a9d8a018e6442963ed388ff3b6c1459850cd8f316d5f1796528f38405758" \-H 'Content-Type:application/json' \-d '{"msgtype":"text","text":{"content":"android 米易通物联网 release version build success"},"at":{"atMobiles":["13915272257"]}}'
  artifacts:
    paths:
      - app/build/outputs/apk/
  tags:
    - android  # 指定脚本在有 android 标签的 runner 上运行


# 利用标签打release包，格式：“x.x.x”
release:
  stage: build
  only:
    - /^[\d]+\.[\d]+\.[\d]+$/
  #  except:
  #    - branches
  script:
    - ./gradlew assembleRelease
    - curl "https://oapi.dingtalk.com/robot/send?access_token=4946a9d8a018e6442963ed388ff3b6c1459850cd8f316d5f1796528f38405758" \-H 'Content-Type:application/json' \-d '{"msgtype":"text","text":{"content":"android 米易通物联网 release version build success"},"at":{"atMobiles":["13915272257"]}}'
  artifacts:
    paths:
      - app/build/outputs/apk/
  tags:
    - android  # 指定脚本在有 android 标签的 runner 上运行

uploadToFir:
  stage: deploy
  script:
    #    - |
    #      export App_Version_Name=$(grep -E "appVersionName" config.gradle | cut -d "'" -f2)
    #      echo "appVersionName is $App_Version_Name"
    #      echo "apk url is app/build/outputs/apk/production/release/mcloudapp_iot_${App_Version_Name}_${CI_COMMIT_SHA:0:7}.apk"
    #      curl -F "file=@app/build/outputs/apk/production/release/mcloudapp_iot_${App_Version_Name}_${CI_COMMIT_SHA:0:7}.apk" -F "uKey=0a4359bc88687c92d393d8019df40771" -F "_api_key=64454bf76fe2abd8dec45200c11fc93b" -F "updateDescription=1.测试 GitLab CI 自动构建打包 apk 并自动上传" https://qiniu-storage.pgyer.com/apiv1/app/upload
    - curl "https://oapi.dingtalk.com/robot/send?access_token=4946a9d8a018e6442963ed388ff3b6c1459850cd8f316d5f1796528f38405758" \-H 'Content-Type:application/json' \-d '{"msgtype":"text","text":{"content":"android TPSCITest upload success"},"at":{"atMobiles":["13915272257"]}}'
  tags:
    - test