image: jangrewe/gitlab-ci-android

cache:
  key: ${CI_PROJECT_ID}
  paths:
    - .gradle/

before_script:
  - export GRADLE_USER_HOME=$(pwd)/.gradle
  - chmod +x ./gradlew

stages:
  - build

Debug:
  stage: build
  script:
    - ./gradlew assembleDebug
    - curl "https://oapi.dingtalk.com/robot/send?access_token=44d67f896e57515b7c86dc22d46e958d6b6125805259b15cc43ebf468fc8fc27" -XPOST -H 'content-type:application/json' -d '{"msgtype":"text","text":{"content":"@13915272257【米易通2.0】打包完成，下载地址：https://www.pgyer.com/miyitong"},"at":{"atMobiles":["13915272257"],"isAtAll":false}}'
  artifacts:
    paths:
      - app/build/outputs/apk/mcloudapp_v2_debug.apk

#Release:
#  stage: build
#  script:
#    - ./gradlew assembleRelease
#    - curl "https://oapi.dingtalk.com/robot/send?access_token=44d67f896e57515b7c86dc22d46e958d6b6125805259b15cc43ebf468fc8fc27" -XPOST -H 'content-type:application/json' -d '{"msgtype":"text","text":{"content":"@13915272257【米易通2.0】打包完成，下载地址：https://www.pgyer.com/miyitong"},"at":{"atMobiles":["13915272257"],"isAtAll":false}}'
#  artifacts:
#    paths:
#      - app/build/outputs/apk/mcloudapp_v2.apk