

buildscript {

    repositories {
        google()
        mavenCentral()
        jcenter()
        //GitHub 开源代码库
        maven { url 'https://jitpack.io' }
        // 配置HMS Core SDK的Maven仓地址。
        maven {url 'https://developer.huawei.com/repo/'}
        //【友盟+】SDK新maven仓库地址
        maven { url 'https://repo1.maven.org/maven2/' }
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:7.2.0'
    }
}




task clean(type: Delete) {
    rootProject.allprojects {
        delete(it.buildDir)
    }
}
