ext {
    android = [
            applicationId    : 'com.shmedo.mcloudapp.iot',
            compileSdkVersion: 30,
            minSdkVersion    : 24,
            targetSdkVersion : 30,
            appVersionName      : '3.1.2'
    ]
    thirdLib = [
            appcompat                    : '1.3.1',
            material                     : '1.4.0',
            recyclerview                 : '1.2.1',

            rxjava                       : '3.1.1',
            rxandroid                    : '3.0.0',
            retrofitVersion              : '2.9.0',
            adapterRxjava3               : '2.9.0',
            okHttpVersion                : '5.0.0-alpha.2',

            butterknife                  : '10.2.1',
            butterknifeCompiler          : '10.2.1',

            glideVersion                 : '4.12.0',
            circleimageview              : '3.0.0',
            banner                       : '2.1.0',

            materialDialogsCore          : '0.9.6.0',
            xpopupVersion                : '2.6.7',
            dialogxVersion               : '0.0.43',
            ToastUtils                   : '9.6',

            switchbutton                 : '2.0.0',

            pgyerSdk                     : '4.2.5',
            buglyCrashReport             : '3.4.4',
            buglyNativeCrashReport       : '3.9.2',

            timberVersion                : '5.0.1',
            Log4a                        : '1.5.0',
            Logcat                       : '9.8',

            permissionx                  : '1.5.0',

            swiperefreshlayout           : '1.1.0',
            SmartRefreshLayout           : '2.0.3',

            SwipeRecyclerView            : '1.3.2',
            BaseRecyclerViewAdapterHelper: '3.0.4',

            bsxShare                     : '0.9.3',

            RangeSeekBar                 : 'v3.0.0',

            amapNavi                     : '8.0.0_3dmap8.0.0',
            amapLocation                 : '5.4.0',
            amapSearch                   : '7.9.0',

            immersionbar                 : '3.0.0',

            nordicsemiScanner            : '1.5.1',
            nordicsemiLog                : '2.3.0',
            nordicsemiBle                : '2.3.1',

            hmsScanVersion               : '2.2.0.300',

            umsdkCommonVersion           : '9.4.4',
            umsdkAsmsVersion             : '1.4.1',
            umsdkApmVersion              : '1.5.2',

            usbSerialVersion             : '3.4.2',

            nettyVersion                 : '4.1.70.Final',

            gsonVersion                  : '2.8.9',

            unpeekLivedataVersion        : '7.2.0-beta1',

            exifinterfaceVersion         : '1.3.3',

            utilcodexVersion             : '1.30.6',


            junit                        : '4.13.2',
            testExtJunit                 : '1.1.3',
            runner                       : '1.4.0',
            espresso                     : '3.4.0'
    ]
}