############################################
# Gradle / JVM?Gradle 8.x ???
############################################
# ????????????CI ?????
org.gradle.jvmargs=-Xmx4g -XX:MaxMetaspaceSize=1g -XX:+UseG1GC -Dfile.encoding=UTF-8

# ???????Gradle 8 ??????????????????
org.gradle.parallel=true
# ??????
org.gradle.caching=true

# ?????????Gradle 8 ?????AGP 8 ??????????????
org.gradle.configuration-cache=true

# ??????? worker ????? CI/????????????
# org.gradle.workers.max=2


############################################
# AndroidX / Jetifier
############################################
android.useAndroidX=true
# ?????????? AndroidX?Jetifier ???????????? support ?????? true
android.enableJetifier=true


############################################
# Kotlin / KAPT ????????? KSP ???? KSP?
############################################
# KAPT ??? worker????????????
kapt.incremental.apt=true
kapt.use.worker.api=true
kapt.include.compile.classpath=false

# Kotlin Daemon ???????????
kotlin.daemon.jvm.options=-Xmx2g


############################################
# R / DataBinding / ??
############################################
# ??? R??????????????
android.nonTransitiveRClass=true

# ??? R?AGP 8.1+ ???????????????????
# android.enableAppCompileTimeRClass=true


############################################
# R8 / ??
############################################
# AGP 8 ??R8 ???????? fullMode ??????????
# android.enableR8.fullMode=true   <-- ????

# ????????????????????????? dex ????????
# -Dcom.android.tools.r8.dexFilePerClassFile=true ???? org.gradle.jvmargs ?
# org.gradle.jvmargs=... -Dcom.android.tools.r8.dexFilePerClassFile=true