##
## Copyright 2022 Google LLC
##
## Licensed under the Apache License, Version 2.0 (the "License");
## you may not use this file except in compliance with the License.
## You may obtain a copy of the License at
##
##     https://www.apache.org/licenses/LICENSE-2.0
##
## Unless required by applicable law or agreed to in writing, software
## distributed under the License is distributed on an "AS IS" BASIS,
## WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
## See the License for the specific language governing permissions and
## limitations under the License.
##
[versions]
activityKtx = "1.9.1"
agp = "8.3.2"
agentweb = "v5.0.6-androidx"
appcompat = "1.7.0"
amapLocation = "6.4.3"
amapSearch = "9.7.0"
baseRecyclerView = "1.5.8"
compileSdk = "34"
constraintLayout = "2.1.4"
crashreport = "4.1.9.2"
customactivityoncrash = "2.4.0"
dateTimePicker = "0.6.3"
dialogX = "0.0.48"
espresso = "3.6.1"
flexbox = "3.0.0"
fragmentKtx = "1.8.2"
getActivityLogcat = "11.8"
glide = "4.16.0"
hmsScan = "2.12.0.301"
immersionbar = "3.2.2"
junit = "4.13.2"
koinAndroid = "3.5.4"
kotlin = "1.9.23"
keyboardvisibilityevent = "3.0.0-RC3"
ksp = "1.9.23-1.0.19"
leakcanary = "2.12"
lifecycle = "2.8.4"
legacyV4 = "1.0.0"
material = "1.12.0"
materialDialogs = "3.3.0"
minSdk = "24"
mmkv = "1.3.4"
moshiVersion = "1.15.1"
navigation = "2.7.7"
nettyAll = "4.1.110.Final"
nordicsemiBleKtx = "2.7.5"
nordicsemiScanner = "1.6.0"
okhttpVersion = "4.12.0"
pictureselector = "v3.11.1"
rangeSeekBar = "v3.0.0"
room = "2.6.1"
rxhttp = "3.2.7"
share2 = "0.9.3"
smoothNavigation = "4.0.0"
startupRuntime = "1.1.1"
strictDatabinding = "6.2.0"
switchbutton = "2.1.0"
tableView = "v0.8.9.4"
targetSdk = "34"
testExtJunit = "1.2.1"
timber = "5.0.1"
toastUtils = "12.6"
unpeekLivedata = "7.8.0"
utilcodex = "1.31.1"
xpopup = "2.9.19"
xUpdate = "2.1.5"
xxPermission = "18.63"

[libraries]
androidx-activity-ktx = { module = "androidx.activity:activity-ktx", version.ref = "activityKtx" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
androidx-constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintLayout" }
androidx-espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "espresso" }
androidx-fragment-ktx = { module = "androidx.fragment:fragment-ktx", version.ref = "fragmentKtx" }
androidx-lifecycle-livedata-ktx = { module = "androidx.lifecycle:lifecycle-livedata-ktx", version.ref = "lifecycle" }
androidx-lifecycle-process = { module = "androidx.lifecycle:lifecycle-process", version.ref = "lifecycle" }
androidx-lifecycle-viewmodel-ktx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycle" }
androidx-legacy-support = { module = "androidx.legacy:legacy-support-v4", version.ref = "legacyV4" }
androidx-navigation-fragment-ktx = { module = "androidx.navigation:navigation-fragment-ktx", version.ref = "navigation" }
#androidx-navigation-ui-ktx = { module = "androidx.navigation:navigation-ui-ktx", version.ref = "navigation" }
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }
androidx-room-ktx = { module = "androidx.room:room-ktx", version.ref = "room" }
androidx-startup-runtime = { module = "androidx.startup:startup-runtime", version.ref = "startupRuntime" }
androidx-test-ext-junit = { module = "androidx.test.ext:junit", version.ref = "testExtJunit" }
agentweb-core = { module = "com.github.Justson.AgentWeb:agentweb-core", version.ref = "agentweb" }
amap-location = { module = "com.amap.api:location", version.ref = "amapLocation" }
amap-search = { module = "com.amap.api:search", version.ref = "amapSearch" }
bugly-crashreport = { module = "com.tencent.bugly:crashreport", version.ref = "crashreport" }
customactivityoncrash = { module = "cat.ereza:customactivityoncrash", version.ref = "customactivityoncrash" }
datetime-picker = { module = "com.github.loper7:DateTimePicker", version.ref = "dateTimePicker" }
dialogx = { module = "com.kongzue.dialogx:DialogX", version.ref = "dialogX" }
flexbox = { module = "com.google.android.flexbox:flexbox", version.ref = "flexbox" }
#getActivity-logcat = { module = "com.github.getActivity:Logcat", version.ref = "getActivityLogcat" }
getActivity-xxpermission = { module = "com.github.getActivity:XXPermissions", version.ref = "xxPermission" }
glide = { module = "com.github.bumptech.glide:glide", version.ref = "glide" }
hms-scan = { module = "com.huawei.hms:scan", version.ref = "hmsScan" }
immersionbar = { module = "com.geyifeng.immersionbar:immersionbar", version.ref = "immersionbar" }
immersionbar-ktx = { module = "com.geyifeng.immersionbar:immersionbar-ktx", version.ref = "immersionbar" }
junit = { module = "junit:junit", version.ref = "junit" }
keyboardvisibilityevent = { module = "net.yslibrary.keyboardvisibilityevent:keyboardvisibilityevent", version.ref = "keyboardvisibilityevent" }
koin-android = { module = "io.insert-koin:koin-android", version.ref = "koinAndroid" }
kotlin-stdlib-jdk8 = { module = "org.jetbrains.kotlin:kotlin-stdlib-jdk8", version.ref = "kotlin" }
#kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines" }
#kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
kunminx-unpeek-livedata = { module = "com.kunminx.arch:unpeek-livedata", version.ref = "unpeekLivedata" }
kunminx-smooth-navigation = { module = "com.kunminx.arch:smooth-navigation", version.ref = "smoothNavigation" }
kunminx-strict-databinding = { module = "com.github.KunMinX.Strict-DataBinding:strict_databinding", version.ref = "strictDatabinding" }
#leakcanary-android = { module = "com.squareup.leakcanary:leakcanary-android", version.ref = "leakcanary" }
liangjingkanji-brv = { module = "com.github.liangjingkanji:BRV", version.ref = "baseRecyclerView" }
lucksiege-pictureselector = { module = "io.github.lucksiege:pictureselector", version.ref = "pictureselector" }
lucksiege-compress = { module = "io.github.lucksiege:compress", version.ref = "pictureselector" }
lucksiege-camerax = { module = "io.github.lucksiege:camerax", version.ref = "pictureselector" }
material = { module = "com.google.android.material:material", version.ref = "material" }
material-dialogs-lifecycle = { module = "com.afollestad.material-dialogs:lifecycle", version.ref = "materialDialogs" }
material-dialogs-core = { module = "com.afollestad.material-dialogs:core", version.ref = "materialDialogs" }
material-dialogs-datetime = { module = "com.afollestad.material-dialogs:datetime", version.ref = "materialDialogs" }
material-dialogs-bottomsheets = { module = "com.afollestad.material-dialogs:bottomsheets", version.ref = "materialDialogs" }
mmkv = { module = "com.tencent:mmkv", version.ref = "mmkv" }
moshi = { module = "com.squareup.moshi:moshi", version.ref = "moshiVersion" }
moshi-kotlin-codegen = { module = "com.squareup.moshi:moshi-kotlin-codegen", version.ref = "moshiVersion" }
netty-all = { module = "io.netty:netty-all", version.ref = "nettyAll" }
nordicsemi-ble-ktx = { module = "no.nordicsemi.android:ble-ktx", version.ref = "nordicsemiBleKtx" }
nordicsemi-scanner = { module = "no.nordicsemi.android.support.v18:scanner", version.ref = "nordicsemiScanner" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttpVersion" }
okhttp-logging-interceptor = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "okhttpVersion" }
rangeSeekBar = { module = "com.github.Jay-Goo:RangeSeekBar", version.ref = "rangeSeekBar" }
rxhttp = { module = "com.github.liujingxing.rxhttp:rxhttp", version.ref = "rxhttp" }
rxhttp-compiler = { module = "com.github.liujingxing.rxhttp:rxhttp-compiler", version.ref = "rxhttp" }
rxhttp-converter-moshi = { module = "com.github.liujingxing.rxhttp:converter-moshi", version.ref = "rxhttp" }
share2 = { module = "gdut.bsx:share2", version.ref = "share2" }
switchbutton-library = { module = "com.kyleduo.switchbutton:library", version.ref = "switchbutton" }
tableview = { module = "com.github.evrencoskun:TableView", version.ref = "tableView" }
timber = { module = "com.jakewharton.timber:timber", version.ref = "timber" }
toastutils = { module = "com.github.getActivity:ToastUtils", version.ref = "toastUtils" }
utilcodex = { module = "com.blankj:utilcodex", version.ref = "utilcodex" }
xpopup = { module = "com.github.li-xiaojun:XPopup", version.ref = "xpopup" }
xuexiangjys-xupdate = { module = "com.github.xuexiangjys:XUpdate", version.ref = "xUpdate" }


[bundles]
material-dialogs = ["material-dialogs-lifecycle", "material-dialogs-core", "material-dialogs-datetime", "material-dialogs-bottomsheets"]
pictureselector = ["lucksiege-pictureselector", "lucksiege-compress", "lucksiege-camerax"]

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
android-test = { id = "com.android.test", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-kapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
kotlin-parcelize = { id = "org.jetbrains.kotlin.plugin.parcelize", version.ref = "kotlin" }

