apply plugin: 'com.android.library'

android {
    compileSdkVersion rootProject.android.compileSdkVersion

    defaultConfig {
        minSdkVersion rootProject.android.minSdkVersion
        targetSdkVersion rootProject.android.targetSdkVersion
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        consumerProguardFiles 'consumer-rules.pro'
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}

dependencies {
    api fileTree(dir: 'libs', include: ['*.jar'])
    api "androidx.appcompat:appcompat:$rootProject.thirdLib.appcompat"
    implementation "androidx.recyclerview:recyclerview:$rootProject.thirdLib.recyclerview"
    api "com.google.code.gson:gson:$rootProject.thirdLib.gsonVersion"

    api "org.greenrobot:eventbus:$rootProject.thirdLib.eventbus"

    api "com.jakewharton.timber:timber:$rootProject.thirdLib.timberVersion"
    //一个基于 mmap, 高性能、高可用的 Android 日志收集框架
    api "com.github.pqpo:Log4a:$rootProject.thirdLib.Log4a"

    api "androidx.exifinterface:exifinterface:$rootProject.thirdLib.exifinterfaceVersion"
    api 'com.zhihu.android:matisse:0.5.3-beta3'
    api "io.netty:netty-all:$rootProject.thirdLib.nettyVersion"
    api 'com.thanosfisherman.elvis:elvis:3.0'

    api "no.nordicsemi.android:ble:$rootProject.thirdLib.nordicsemiBle"

    api "com.kunminx.arch:unpeek-livedata:$rootProject.thirdLib.unpeekLivedataVersion"

    //AndroidUtilCode 是一个强大易用的安卓工具类库
    api "com.blankj:utilcodex:$rootProject.thirdLib.utilcodexVersion"

    testImplementation "junit:junit:$rootProject.thirdLib.junit"
    androidTestImplementation "androidx.test.ext:junit:$rootProject.thirdLib.testExtJunit"
    androidTestImplementation "androidx.test.espresso:espresso-core:$rootProject.thirdLib.espresso"
}
