plugins {
    id 'com.android.application'
    id 'org.jetbrains.kotlin.android'
    id 'kotlin-kapt'
    alias(libs.plugins.android.ksp)
}

/**
 * 获取APP名字
 * @return
 */
def getAppName() {
    return 'mcloudapp_iot'
}

/**
 * 获取Git库HEAD的SHA1码前5位
 */
def gitShortCommitId() {
    def cmd = 'git rev-parse --short HEAD'
    cmd.execute().text.trim()
}

/**
 * 获取Git库的提交次数
 */
def getReversion() {
    def buildnum = 1
    try {
        //底层使用的是 Runtime.getRuntime().exec()去执行
        def getGit = 'git rev-list --count HEAD'.execute()
        if (getGit.text.trim() == '')
            buildnum = versionMajor * 10000 + versionMinor * 1000 + versionPatch * 100
        else {
            buildnum = getGit.text.trim().toInteger()
        }
    } catch (e) {
        e.printStackTrace()
    }
    return buildnum
}

android {
    compileSdk libs.versions.compileSdk.get().toInteger()
    defaultConfig {
        applicationId "com.shmedo.mcloudapp.iot"
        minSdk = libs.versions.minSdk.get().toInteger()
        targetSdk = libs.versions.targetSdk.get().toInteger()
        versionCode getReversion()
        versionName '3.2.0'
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        ndk {
            //设置支持的SO库架构（开发者可以根据需要，选择一个或多个平台的so）
            abiFilters  "arm64-v8a","armeabi-v7a"//"x86_64","x86", "armeabi", "armeabi-v7a"
        }
    }
    signingConfigs {
        release {
            keyAlias "mcloud"
            keyPassword "420529"
            storeFile file("../app/mcloud.jks")
            storePassword "420529"
            v1SigningEnabled true
            v2SigningEnabled true
        }
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
            signingConfig signingConfigs.release
        }
//        debug {
//            minifyEnabled false
//            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
//            signingConfig signingConfigs.release
//        }
    }
    sourceSets {
        main {
            jniLibs.srcDirs = ['libs']
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    kotlinOptions {
        jvmTarget = '1.8'
    }

    buildFeatures {
        dataBinding true
        viewBinding true
    }

    packagingOptions {
        exclude 'META-INF/*'
    }

    // Specifies one flavor dimension.
    flavorDimensions "version"
    productFlavors {
        production {//正式发布版本
            dimension "version"
            applicationId "com.shmedo.mcloudapp.iot"
            resValue "string", "app_name", "米易通物联网"   // 设置默认的app_name
            manifestPlaceholders = ["mapApikey"  : "61b252e0afae07eebf71fd8b519b511c",
                                    "buglyAppId" : "09b15cd6a7",
                                    "umengAppkey": "6209cd80226836222738b72b"]

            buildConfigField "String", "Dingding_APP_ID", "\"dingoa6lbfnghbtn0xeju0\""
        }
    }
    applicationVariants.all { variant ->
        sourceSets {
            def name = variant.name
            getByName(name) {  //告知IDE，ksp生成的kotlin代码
                kotlin.srcDir("build/generated/ksp/$name/kotlin")
            }
        }
        variant.outputs.each { output ->
            def fileName
            //输出文件夹
            if ('debug' == variant.buildType.name) {
                fileName = "${getAppName()}_v${android.defaultConfig.versionName}_${gitShortCommitId()}_${getReversion()}_debug.apk"
            } else {
                fileName = "${getAppName()}_v${android.defaultConfig.versionName}_${gitShortCommitId()}_${variant.productFlavors[0].name}.apk"
            }
            output.outputFileName = fileName
        }
    }
}

dependencies {
    implementation libs.androidx.legacy.support.v4
    testImplementation libs.junit
    androidTestImplementation libs.androidx.test.ext.junit
    androidTestImplementation libs.androidx.espresso.core

    implementation fileTree(dir: 'libs', include: ['*.jar', '*.aar'])
    implementation project(":lib_ble")
    implementation project(":lib_tcp")
    implementation project(":lib_network")
    implementation project(":lib_core")
    implementation libs.kotlin.stdlib.jdk8
    implementation libs.androidx.constraintlayout
    implementation libs.flexbox
    implementation libs.androidx.core.ktx
    implementation libs.androidx.appcompat
    implementation libs.material
    implementation libs.androidx.activity.ktx
    implementation libs.androidx.fragment.ktx
    implementation libs.androidx.lifecycle.livedata.ktx
    implementation libs.androidx.lifecycle.viewmodel.ktx
    implementation libs.kunminx.unpeek.livedata
    implementation libs.kunminx.strict.databinding
    implementation libs.kunminx.smooth.navigation
    //通过 exclude 把对官方 java 包的依赖排除了，引用默认指向 smooth-Navigation
    implementation(libs.androidx.navigation.fragment.ktx) {
        exclude group: 'androidx.navigation', module: "navigation-fragment"
    }
//    implementation libs.androidx.navigation.ui.ktx

    //透明系统栏设置基础依赖包，必须要依赖
    implementation libs.immersionbar
    // kotlin扩展（可选）
    implementation libs.immersionbar.ktx
    // 权限请求框架：https://github.com/getActivity/XXPermissions
    implementation libs.getActivity.xxpermission
    //Material Dialog
    implementation libs.bundles.material.dialogs
    //Powerful and Beautiful Popup for Android，can absolutely replace Dialog，PopupWindow，PopupMenu，BottomSheet，DrawerLayout，Spinner...
    implementation libs.xpopup
    implementation libs.dialogx
    //Toast 吐司
    implementation libs.getActivity.toastutils
    implementation libs.datetime.picker

    //下拉刷新
    implementation libs.bundles.refreshlayout
    //RecyclerView侧滑菜单，Item拖拽，滑动删除Item，自动加载更多，HeaderView，FooterView，Item分组黏贴
    implementation libs.recyclerview.x
    //一个强大并且灵活的RecyclerViewAdapter
    implementation libs.base.recyclerview.adapter.helper
    //StateView is an invisible, zero-sized View that can be used to lazily inflate loadingView/emptyView/retryView/anyView at runtime.
    implementation libs.stateview

    implementation libs.agentweb.core

    //开关 Button
    implementation libs.switchbutton.library
    implementation libs.progressbutton
    // 一款美观强大的支持单向、双向范围选择、分步、垂直、高度自定义的SeekBar
    implementation libs.rangeSeekBar
    //Android Library to handle software keyboard visibility change event.
    implementation libs.keyboardvisibilityevent

    //华为扫码服务
    implementation libs.hms.scan

    //利用了 Android 系统的原生 API 实现了分享功能
    implementation libs.share2
    //高德地图导航
    implementation libs.amap3dmap
    //异常处理页面
    implementation libs.customactivityoncrash
    //异常信息上报组件
    implementation libs.bugly.crashreport
    debugImplementation libs.leakcanary.android
    //日志调试框架：https://github.com/getActivity/Logcat
//    debugImplementation libs.getActivity.logcat

    // Glide
    implementation libs.glide

    //A logger with a small, extensible API which provides utility on top of Android's normal Log class.
    implementation libs.timber
    //AndroidUtilCode 是一个强大易用的安卓工具类库
    implementation libs.utilcodex
    implementation libs.mmkv

    implementation libs.moshi
    ksp libs.moshi.kotlin.codegen

}
