plugins {
    id 'com.android.application'
    id 'kotlin-android'
    id 'kotlin-kapt'
    alias(libs.plugins.android.ksp)
}

/**
 * 获取APP名字
 * @return
 */
def getAppName() {
    return 'mcloudapp_iot'
}

/**
 * 获取Git库HEAD的SHA1码前5位
 */
def gitShortCommitId() {
    def cmd = 'git rev-parse --short HEAD'
    cmd.execute().text.trim()
}

/**
 * 获取Git库的提交次数
 */
def gitVersionCode() {
    def buildnum = 1
    try {
        //底层使用的是 Runtime.getRuntime().exec()去执行
        def getGit = 'git rev-list --count HEAD'.execute()
        if (getGit.text.trim() == '')
            buildnum = versionMajor * 10000 + versionMinor * 1000 + versionPatch * 100
        else {
            buildnum = getGit.text.trim().toInteger()
        }
    } catch (e) {
        e.printStackTrace()
    }
    return buildnum
}

android {
    compileSdk libs.versions.compileSdk.get().toInteger()
    defaultConfig {
        applicationId "com.shmedo.mcloudapp.iot"
        minSdk = libs.versions.minSdk.get().toInteger()
        targetSdk = libs.versions.targetSdk.get().toInteger()
        versionCode getReversion()
        versionName '3.2.0'
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        ndk {
            //设置支持的SO库架构（开发者可以根据需要，选择一个或多个平台的so）
            abiFilters "armeabi-v7a"//"x86_64","x86", "armeabi", "armeabi-v7a"
        }
    }
    buildFeatures {
        dataBinding true
        viewBinding true
    }

    sourceSets {
        main {
            jniLibs.srcDirs = ['libs']
        }
    }

    signingConfigs {
        release {
            keyAlias "mcloud"
            keyPassword "420529"
            storeFile file("../app/mcloud.jks")
            storePassword "420529"
            v1SigningEnabled true
            v2SigningEnabled true
        }
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
            signingConfig signingConfigs.release
        }
        debug {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
            signingConfig signingConfigs.release
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    packagingOptions {
        exclude 'META-INF/*'
    }

    // Specifies one flavor dimension.
    flavorDimensions "version"
    productFlavors {
        production {//正式发布版本
            dimension "version"
            applicationId rootProject.android.applicationId
            resValue "string", "app_name", "米易通物联网"   // 设置默认的app_name
            manifestPlaceholders = ["mapApikey"  : "61b252e0afae07eebf71fd8b519b511c",
                                    "buglyAppId" : "09b15cd6a7",
                                    "umengAppkey": "6209cd80226836222738b72b"]

            buildConfigField "String", "Dingding_APP_ID", "\"dingoa6lbfnghbtn0xeju0\""
        }
    }
    applicationVariants.all { variant ->
        variant.outputs.each { output ->
            def fileName
            //输出文件夹
            if ('debug'.equals(variant.buildType.name)) {
                fileName = getAppName() + "_v${android.defaultConfig.versionName}_${gitVersionCode()}_debug.apk"
            } else {
                fileName = getAppName() + "_v" + android.defaultConfig.versionName + "_" + gitShortCommitId() + "_" + variant.productFlavors[0].name + ".apk"
            }
            output.outputFileName = fileName
        }
    }
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar', '*.aar'])

}
