
# \u63D0\u53D6\u6B63\u5F0F\u7248\u672C\u53F7
MAJOR_VERSION=5
MINOR_VERSION=3
PATCH_VERSION=20

# \u63D0\u53D6\u6D4B\u8BD5\u7248\u672C\u53F7
TEST_MAJOR_VERSION=5
TEST_MINOR_VERSION=3
TEST_PATCH_VERSION=39

#  \u901A\u7528 versionCode
VERSION_CODE=2511051