plugins {
    id 'com.android.library'
    id 'org.jetbrains.kotlin.android'
    alias(libs.plugins.android.ksp)
}

android {
    namespace 'com.shmedo.lib.network'
    compileSdk libs.versions.compileSdk.get().toInteger()

    defaultConfig {
        minSdk = libs.versions.minSdk.get().toInteger()

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        consumerProguardFiles "consumer-rules.pro"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    kotlinOptions {
        jvmTarget = '1.8'
    }

    //ksp传参方式
    ksp {
        arg("rxhttp_rxjava", "$libs.versions.rxjava")
    }
}

dependencies {
    testImplementation libs.junit
    androidTestImplementation libs.androidx.test.ext.junit
    androidTestImplementation libs.androidx.espresso.core
    implementation fileTree(dir: 'libs', include: ['*.jar', '*.aar'])
    implementation project(":lib_core")

    implementation libs.androidx.core.ktx
    //A logger with a small, extensible API which provides utility on top of Android's normal Log class.
    implementation libs.timber
    //AndroidUtilCode 是一个强大易用的安卓工具类库
    implementation libs.utilcodex
    implementation libs.mmkv

    implementation libs.okhttp3.logging.interceptor
    api libs.rxjava
    api libs.rxandroid
    api libs.rxhttp
    ksp libs.rxhttp.compiler
    implementation libs.rxhttp.converter.moshi

    implementation libs.moshi
    ksp libs.moshi.kotlin.codegen

    // 一个轻量级、高可用性的Android版本更新框架
    implementation libs.xuexiangjys.xupdate
    implementation libs.okhttputils
}